name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        zip -r powercurve.zip . -x "venv/*" "*.git*" "__pycache__/*"
        aws elasticbeanstalk create-application-version \
          --application-name "PowerCurveApp" \
          --version-label "v-${{ github.sha }}" \
          --source-bundle S3Bucket="elasticbeanstalk-bucket",S3Key="powercurve.zip"
        aws elasticbeanstalk update-environment \
          --application-name "PowerCurveApp" \
          --environment-name "flask-env" \
          --version-label "v-${{ github.sha }}"